### ISSUE TITLE
Snippets don't work in HTML

### ISSUE THREAD

**Issue by thomastalsma** [hubsta/acf-snippet-vsc#7]
Hi,
I love using these snippets, thanks so much for putting them together!

I have just noticed that they don't seem to work when in HTML. The autocomplete never shows.
When including them in `<?php  ?>` tags, they fire but you end up with duplicate php tags as they're included in all the snippets.

Cheers

**Comment by hubsta** [comment]
Hey @TT21 ,

Thanks for using the snippet! I've gone ahead and added this feature into the plugin. Let us know if there are any issues.
