### ISSUE TITLE
`field:image:object` in VScode doesn't have `$` in variable name

### ISSUE THREAD

**Issue by brantleyenglish** [hubsta/acf-snippet-vsc#8]
When we use the `field:image:object` this is what we get:
![screenshot of ACF snippet in vscode](http://sodiumhalogen.com/up_be/Screen%20Shot%202017-09-28%20at%207.42.30%20AM-0XalW5g2Vt.png)

It looks like your repo here on Github is correct. Awesome!
Are you guys able to update the VScode extension?

**Comment by michaelmano** [comment]
Thanks for letting us know about the issue @brantleyenglish 
I'll get onto it now 👍

**Comment by michaelmano** [comment]
The issue is vscode is escaping all $ used within the snippets, not just the image field.
I will have to update all variables to use a double $$ to get around this.
